import { MagicCard, makeCharacter } from "./Magic";

export enum UniqueAbility {
  Fireball = "Fireball",
  Heal = "Heal",
  Shield = "Shield",
  Poison = "Poison",
  Bomber = "Bomber",
  ManaBoost = "Mana Boost",
  ElectricBlast = "Electric Blast",
  None = "None"
}

export const allCards: MagicCard[] = [
  {
    name: "Tio",
    image: makeCharacter(),
    damage: 7,
    realHealth: 3,
    health: 3,
    uniqueAbility: UniqueAbility.Fireball,
  },
  {
    name: "Aviv",
    image: makeCharacter(),
    damage: 0,
    realHealth: 10,
    health: 10,
    uniqueAbility: UniqueAbility.Poison,
  },
  {
    name: "Ariel",
    image: makeCharacter(),
    damage: 3,
    realHealth: 8,
    health: 8,
    uniqueAbility: UniqueAbility.Shield,
  },
  {
    name: "Ori",
    image: makeCharacter(),
    damage: 5,
    realHealth: 10,
    health: 10,
    uniqueAbility: UniqueAbility.ManaBoost,
  },
  {
    name: "Tal",
    image: makeCharacter(),
    damage: 0,
    realHealth: 20,
    health: 20,
    uniqueAbility: UniqueAbility.Bomber,
  },
  {
    name: "Yoshihara",
    image: makeCharacter(),
    damage: 5,
    realHealth: 5,
    health: 5,
    uniqueAbility: UniqueAbility.ManaBoost,
  },
  {
    name: "Iran",
    image: makeCharacter(),
    damage: 3,
    realHealth: 2,
    health: 2,
    uniqueAbility: UniqueAbility.Fireball,
  },
  {
    name: "Eshel",
    image: makeCharacter(),
    damage: 3,
    realHealth: 7,
    health: 7,
    uniqueAbility: UniqueAbility.Heal,
  },
  {
    name: "Amos",
    image: makeCharacter(),
    damage: 2,
    realHealth: 10,
    health: 10,
    uniqueAbility: UniqueAbility.Shield,
  },
  {
    name: "Toxic Alchemist",
    image: makeCharacter(),
    damage: 4,
    realHealth: 3,
    health: 3,
    uniqueAbility: UniqueAbility.Poison,
  },
  {
    name: "Dual-Blade Warrior",
    image: makeCharacter(),
    damage: 6,
    realHealth: 5,
    health: 5,
    uniqueAbility: UniqueAbility.Poison,
  },
  {
    name: "Mana Spirit",
    image: makeCharacter(),
    damage: 3,
    realHealth: 4,
    health: 4,
    uniqueAbility: UniqueAbility.ManaBoost,
  },
  {
    name: "Gurdian Angel",
    image: makeCharacter(),
    damage: 0,
    realHealth: 13,
    health: 13,
    uniqueAbility: UniqueAbility.Heal,
  },
  {
    name: "Tio",
    image: makeCharacter(),
    damage: 7,
    realHealth: 3,
    health: 3,
    uniqueAbility: UniqueAbility.Fireball,
  },
  {
    name: "Aviv",
    image: makeCharacter(),
    damage: 0,
    realHealth: 10,
    health: 10,
    uniqueAbility: UniqueAbility.Poison,
  },
  {
    name: "Ariel",
    image: makeCharacter(),
    damage: 3,
    realHealth: 8,
    health: 8,
    uniqueAbility: UniqueAbility.Shield,
  },
  {
    name: "Raisfeld",
    image: makeCharacter(),
    damage: 4,
    realHealth: 10,
    health: 10,
    uniqueAbility: UniqueAbility.ElectricBlast,
  },
  {
    name: "Raisfeld",
    image: makeCharacter(),
    damage: 4,
    realHealth: 10,
    health: 10,
    uniqueAbility: UniqueAbility.ElectricBlast,
  },
  {
    name: "Raisfeld",
    image: makeCharacter(),
    damage: 4,
    realHealth: 10,
    health: 10,
    uniqueAbility: UniqueAbility.ElectricBlast,
  },
  {
    name: "Ori",
    image: makeCharacter(),
    damage: 5,
    realHealth: 10,
    health: 10,
    uniqueAbility: UniqueAbility.ManaBoost,
  },
  {
    name: "Tal",
    image: makeCharacter(),
    damage: 0,
    realHealth: 20,
    health: 20,
    uniqueAbility: UniqueAbility.Bomber,
  },
  {
    name: "Yoshihara",
    image: makeCharacter(),
    damage: 5,
    realHealth: 5,
    health: 5,
    uniqueAbility: UniqueAbility.ManaBoost,
  },
  {
    name: "Iran",
    image: makeCharacter(),
    damage: 3,
    realHealth: 2,
    health: 2,
    uniqueAbility: UniqueAbility.Fireball,
  },
  {
    name: "Eshel",
    image: makeCharacter(),
    damage: 3,
    realHealth: 7,
    health: 7,
    uniqueAbility: UniqueAbility.Heal,
  },
  {
    name: "Amos",
    image: makeCharacter(),
    damage: 2,
    realHealth: 10,
    health: 10,
    uniqueAbility: UniqueAbility.Shield,
  },
  {
    name: "Toxic Alchemist",
    image: makeCharacter(),
    damage: 4,
    realHealth: 3,
    health: 3,
    uniqueAbility: UniqueAbility.Poison,
  },
  {
    name: "Dual-Blade Warrior",
    image: makeCharacter(),
    damage: 6,
    realHealth: 5,
    health: 5,
    uniqueAbility: UniqueAbility.Poison,
  },
  {
    name: "Mana Spirit",
    image: makeCharacter(),
    damage: 3,
    realHealth: 4,
    health: 4,
    uniqueAbility: UniqueAbility.ManaBoost,
  },
  {
    name: "Gurdian Angel",
    image: makeCharacter(),
    damage: 0,
    realHealth: 13,
    health: 13,
    uniqueAbility: UniqueAbility.Heal,
  },
  {
    name: "Nagar",
    image: makeCharacter(),
    damage: 8,
    realHealth: 15,
    health: 15,
    uniqueAbility: UniqueAbility.None,
  }
];